### ISSUE TITLE
SampleApp does not work with Play 1.2.1

### ISSUE THREAD

**Issue by hhubris** [branaway/Japid#10]
I was trying to evaluate Japid for use in a new Play! based project.

I simply created a new Play project

```
play new japid
```

And added this dependency:

```
require:
    - play
    - play -> japid 0.8.3.1
```

And then started the SampleApp

cd modules/japid-0.8.3.1/JapidSample

```
play run
```

The home page can't find any of the Japid classes

```
Compilation error (In /app/controllers/Application.java around line 31)
The file /app/controllers/Application.java could not be compiled. Error raised is : JapidController cannot be resolved to a type

play.exceptions.CompilationException: JapidController cannot be resolved to a type
    at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:246)
    at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:672)
    at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:516)
    at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:278)
    at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:406)
    at play.Play.start(Play.java:453)
    at play.Play.detectChanges(Play.java:563)
    at play.Invoker$Invocation.init(Invoker.java:186)
    at Invocation.HTTP Request(Play!)
^C~ ...
```
